/*

Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/

const allFactorsOfN = n => {
  let factors = [];
  for (let i = 1; i <= n; i++) {
    if (n % i === 0) {
      factors.push(i);
    }
  }
  return factors.length
}

const firstTriangleNumberToHaveOver500Divisors = () => {
  let number = 0;
  let triangleNumber = 0;
  let found = false;
  // increment triangle number
  while (!found) {
    number++;
    triangleNumber += number;
    if (allFactorsOfN(triangleNumber) > 500) {
      found = true;
      break;
    }
    // check amount of all factors
    // if that amount is greater than 500, return triangle number.
  }

  return triangleNumber

};

console.log(firstTriangleNumberToHaveOver500Divisors())

// console.log(allFactorsOfN(28))